name: Build

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Get yabal
        run: |
          wget https://github.com/YabalLang/compiler/releases/latest/download/yabal-runtime-linux-x64.zip
          chmod +x yabal
          unzip yabal-runtime-linux-x64.zip

      - name: Build a8cm (normal)
        run: ./yabal build ./main.yabal

      - run: sed -i 's/const int wait = 150/const int wait = 0/' main.yabal
        shell: bash
        name: Sed main.yabal

      - name: Build a8cm (bot)
        run: ./yabal build ./main.yabal -o bot.asm

      - run: gh release create `git log -n 1 --pretty=format:"%h"` main.asm bot.asm
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        name: Upload release