name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone
        run: git clone https://github.com/YabalLang/compiler/ --depth=1

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build yabal
        run: |
          cd compiler/src/Yabal.Desktop
          dotnet build

      - name: Build a8cm
        run: ./compiler/src/Yabal.Desktop/bin/Debug/net8.0/linux-x64/yabal build ./main.yabal

      - uses: actions/upload-artifact@v3
        with:
          name: main.asm
          path: main.asm